### ISSUE TITLE
ROADMAP - RC1

### ISSUE THREAD

**Issue by robsontenorio** [robsontenorio/mary#71]
**Here is the master plan until first 1.0-RC:**

- [x] **x-file**: file upload with progress status and preview. 
- [x] **x-button** : add “link” property to make it act as ordinary `<a>` with `wire:navigate`. 
- [x] **x-input** :  better formatter instead alpine's money mask.
- [ ] **x-choices** : waiting for Livewire bug fixes to solve some glitches. 
- [x] **x-table**: row link, expandable rows, selectable  rows, no-headers
- [x] **x-menu**: badge property
- [x] **responsive**: check all components responsiveness 
- [x]  **x-modal / x-drawer**: review mobile / resize / trigger 
- [x] **wire:key** - review usage across components 

What else ? 🤔

**Comment by roberto-proj** [comment]
Could you add a stepper component? The same way as [Quasar](https://quasar.dev/vue-components/stepper)?

**Comment by Xety** [comment]
You could add a color picker too, like wireui.

**Comment by robsontenorio** [comment]
@Xety 

Actually colopicker  is pretty straightforward with native HTML. It will use your default OS color picker.


```php
public string $color = '#ff4013';
```

```html
<input type="color" wire:model.live="color" /> 
Color: {{ $color }}   
```

<img width="282" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/cb4f7a49-c021-4b02-9b64-11d216410a66">

**Comment by Xety** [comment]
> @Xety
> 
> Actually colopicker is pretty straightforward with native HTML. It will use your default OS color picker.
> 
> ```
> public string $color = '#ff4013';
> ```
> 
> ```
> <input type="color" wire:model.live="color" /> 
> Color: {{ $color }}   
> ```
> 
> <img alt="image" width="282" src="https://user-images.githubusercontent.com/118955/275532638-cb4f7a49-c021-4b02-9b64-11d216410a66.png"> <img alt="image" width="266" src="https://user-images.githubusercontent.com/118955/275534908-de98f4da-697b-4f5b-8dfd-f3e0f3ec11e1.png">

Yes indeed, but I was thinking about something ore intégrated with daisy design like that :
![Capture d'écran 2023-10-21 140906](https://github.com/robsontenorio/mary/assets/8210023/96da1d31-2541-41ca-9c68-04516c7ab2f9)
